if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]; then
    exec startx
    #/scripts/run_sway.sh
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
