export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(zsh-syntax-highlighting git archlinux common-aliaces sudo systemd
wd cp history-substring-search)

source $ZSH/oh-my-zsh.sh
# User configuration
# Substring histor search
zmodload zsh/terminfo
bindkey "\e[A" history-substring-search-up
bindkey "\e[B" history-substring-search-down

export LESSOPEN="| /usr/bin/source-highlight-esc.sh %s"
export LESS='-R '
export EDITOR='nvim'

export SWEETHOME3D_JAVA3D=1.5

source ~/.profile

# Importh path for systemd
systemctl --user set-environment PATH=$PATH

# Vpn connections
for file in $(ls $HOME/.openvpn); do
    alias_name="vpn-${file%.*}"
    alias $alias_name="sudo openvpn $HOME/.openvpn/$file"
done
#for file in $(ls /etc/openvpn/client); do
    #vpn_name="${file%.conf}"
    #alias vpn-${vpn_name}="sudo systemctl start openvpn-client@$vpn_name"
    #alias vpn-${vpn_name}-status="systemctl status openvpn-client@$vpn_name"
    #alias vpn-${vpn_name}-stop="sudo systemctl stop openvpn-client@$vpn_name"
#done

# Aliaces
alias winmv='convmv -f cp1252 -t cp850 * --notest  && convmv -f cp866 -t utf-8 * --notest'
alias sup='rvm 2.3.3 do sup' # sup mua
alias def='dict -d gcide'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

